2025-08-19 15:05:22,269 - WARNING - Error with socket 36 (('172.17.0.1', 5353))): [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 1276, in sendto
    self._sock.sendto(data, addr)
PermissionError: [Errno 1] Operation not permitted
2025-08-19 15:05:22,282 - WARNING - Error with socket 38 (('192.168.1.252', 5353))): [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 1276, in sendto
    self._sock.sendto(data, addr)
PermissionError: [Errno 1] Operation not permitted
